name: "Validate PR Title"

on:
  # NOTE: Force-pushes from automated PRs (like release-please) do not seem to
  # trigger any of the normal PR triggers (opened, edited, synchronize).  In
  # fact, even an exhaustive list of types will not work.  So here we add
  # triggers for reviews, so that the validation will run after someone
  # approves such a PR.  This is critical since this is a required status check
  # in most of our repos.  If it doesn't run, the PR can't be merged.
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  pull_request_review:

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # When using "Squash and merge" on a PR with only one commit, GitHub
          # will suggest using that commit message instead of the PR title for
          # the merge commit, and it's easy to commit this by mistake. Enable
          # this option to also validate the commit message for one-commit PRs.
          validateSingleCommit: true
          # Opt-in to validate that the PR title matches the single commit to
          # avoid confusion.
          validateSingleCommitMatchesPrTitle: true
